In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("./bank-additional/bank-additional/bank-additional-full.csv",delimiter=";")
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [2]:
df = pd.DataFrame(df)

test = df['housing'].unique()
test = np.sort(test)
print(test)

['no' 'unknown' 'yes']

In [3]:
allowed_y = {'yes', 'no'}

if not set(df['y'].unique()).issubset(allowed_y):
    raise ValueError(
        f"Target column contains values outside {allowed_y}"
    )

# ------------------------------------------------------------------
# 3. Count the occurrences using a cross‑tabulation
# ------------------------------------------------------------------
job_target_counts = pd.crosstab(df['housing'], df['y'])

print("Counts of ‘yes’ / ‘no’ per job category:")
job_target_counts = pd.DataFrame(job_target_counts)
job_target_counts

Counts of ‘yes’ / ‘no’ per job category:

y           no   yes
housing
no       16596  2026
unknown    883   107
yes      19069  2507

In [4]:
job_target_percentages = (
    job_target_counts.div(job_target_counts.sum(axis=1), axis=0) * 100
).round(2)

print("\nPercentages of ‘yes’ / ‘no’ per job category:")
print(job_target_percentages)

Percentages of ‘yes’ / ‘no’ per job category:
y           no    yes
housing
no       89.12  10.88
unknown  89.19  10.81
yes      88.38  11.62

### rata juga, mungkin hapus unknown ? atau smote