In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("./bank-additional/bank-additional/bank-additional-full.csv",delimiter=";")
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [6]:
df = pd.DataFrame(df)

test = df['day_of_week'].unique()
test = np.sort(test)
print(test)

['fri' 'mon' 'thu' 'tue' 'wed']

In [7]:
allowed_y = {'yes', 'no'}
if not set(df['y'].unique()).issubset(allowed_y):
    raise ValueError(
        f"Target column contains values outside {allowed_y}"
    )

# ------------------------------------------------------------------
# 3. Count the occurrences using a cross‑tabulation
# ------------------------------------------------------------------
job_target_counts = pd.crosstab(df['day_of_week'], df['y'])

print("Counts of ‘yes’ / ‘no’ per job category:")
job_target_counts = pd.DataFrame(job_target_counts)
job_target_counts

Counts of ‘yes’ / ‘no’ per job category:

y              no   yes
day_of_week
fri          6981   846
mon          7667   847
thu          7578  1045
tue          7137   953
wed          7185   949

In [8]:
job_target_percentages = (
    job_target_counts.div(job_target_counts.sum(axis=1), axis=0) * 100
).round(2)

print("\nPercentages of ‘yes’ / ‘no’ per job category:")
print(job_target_percentages)

Percentages of ‘yes’ / ‘no’ per job category:
y               no    yes
day_of_week
fri          89.19  10.81
mon          90.05   9.95
thu          87.88  12.12
tue          88.22  11.78
wed          88.33  11.67

### ada beberapa hari yang memiliki jumlah conversion lebih besar dari yang lain, namun tidak terlalu jauh, dan konsep hari saja kadang kurang lengkap tanpa waktu yang lain, seperti jam, tanggal, untuk melihat pola tertentu pada waktu